// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SIMEXPRO.DataAccess.Context
{
    public partial class SIMEXPROContext : DbContext
    {
        public SIMEXPROContext()
        {
        }

        public SIMEXPROContext(DbContextOptions<SIMEXPROContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbProcesoPorOrdenCompraDetalle> tbProcesoPorOrdenCompraDetalle { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tbProcesoPorOrdenCompraDetalle>(entity =>
            {
                entity.HasKey(e => e.poco_Id)
                    .HasName("PK_Prod_tbProcesoPorOrdenCompraDetalle_poco_Id");

                entity.ToTable("tbProcesoPorOrdenCompraDetalle", "Prod");

                entity.Property(e => e.code_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.poco_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.poco_FechaModificacion).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}